### PR TITLE
fix: deep link graph views

### LINKED ISSUE #541: Add a deep link to the new graph to load straight different views
Reported in https://github.com/cowprotocol/explorer/pull/534#issuecomment-1607040889

Add a deep link to the new graph to load straight different views:
 - transfer based
 - trade based

### PR DESCRIPTION
**Pull request by alfetopito**
# Summary

Closes #541 

Fixes deep link for graph views

Also refactored tab selection to avoid the same issue in other places

# To Test

1. Load a batch graph
2. Switch to `trade based` view
3. Reload the page
* The same view should be loaded

* Other views and tabs should remain working as they were

### CODE REVIEW

File: src/apps/explorer/components/TransactionsTableWidget/index.tsx [hunk 1]
```diff
@@ -81,9 +80,10 @@ export const TransactionsTableWidget: React.FC<Props> = ({ txHash }) => {
     setTabViewSelected(TabView[newTabViewName])
   }, [])
 
-  useEffect(() => {
-    history.replace({ search: `?tab=${TabView[tabViewSelected].toLowerCase()}` })
-  }, [history, tabViewSelected])
+  useEffect(
+    () => updateQueryString('tab', TabView[tabViewSelected].toLowerCase()),
+    [tabViewSelected, updateQueryString],
+  )
```
Comment (alfetopito) [inline src/apps/explorer/components/TransactionsTableWidget/index.tsx:86]: The actual fix is to avoid replacing the fill `search` path and instead just update the `tab` key

**Review by elena-zh — APPROVED** [review]
LGTM!

File: src/apps/explorer/components/TransactionsTableWidget/index.tsx [hunk 2]
```diff
@@ -81,9 +80,10 @@ export const TransactionsTableWidget: React.FC<Props> = ({ txHash }) => {
     setTabViewSelected(TabView[newTabViewName])
   }, [])
 
-  useEffect(() => {
-    history.replace({ search: `?tab=${TabView[tabViewSelected].toLowerCase()}` })
-  }, [history, tabViewSelected])
+  useEffect(
+    () => updateQueryString('tab', TabView[tabViewSelected].toLowerCase()),
```
Comment (shoom3301) [inline src/apps/explorer/components/TransactionsTableWidget/index.tsx:84]: Nitpick:
Would be great to move `'tag'` to a const

**Review by shoom3301 — APPROVED** [review]
