### PR TITLE
fix: show only trades belonging to the current page on fills tab

### LINKED ISSUE #445: [2.20]Pagination is not correct on the Fills tab
1. Open https://explorer-dev-git-partial-fills-table-styles-cowswap.vercel.app/gc/orders/0x9f5f18111f22b1912bd8f291b753a6fd85e04cd9f05111520f6108fc052716279fa3c00a92ec5f96b1ad2527ab41b3932efeda58643ff3da/?tab=fills
2. Check the pagination

**AR**: it shows 10 lines per page, but there are 13 lines are displayed

**ER**: it should show 10 lines per page (default selection)

### PR DESCRIPTION
**Pull request by alfetopito**
# Summary

Closes #445 

Fills tab list shows only trades from the current page

# To Test

1. Load an order with >10 trades, such as `0x9f5f18111f22b1912bd8f291b753a6fd85e04cd9f05111520f6108fc052716279fa3c00a92ec5f96b1ad2527ab41b3932efeda58643ff3da`
2. Go to fills tab
* It should show more than 1 page
image
* The list should be limited by default to 10 items
* There should be 10 rows in the table
3. Go to the next page
* It should show the next trades, up to 10 in the page

### CODE REVIEW

**Review by elena-zh — APPROVED** [review]
Cool!

**Review by shoom3301 — APPROVED** [review]

File: src/components/orders/OrderDetails/FillsTable.tsx [hunk 1]
```diff
@@ -327,6 +327,10 @@ const FillsTable: React.FC<Props> = (props) => {
 
   const invertButton = <Icon icon={faExchangeAlt} onClick={invertPrice} />
 
+  const shownTrades = useMemo(() => {
```
Comment (anxolin) [inline src/components/orders/OrderDetails/FillsTable.tsx:330]: ube-mega-nit: It just came to mind cause i went to check the implementation after the name was not immediately clear, i find `tadesCurrentPage` more specific. Pls ignore this comment (thinking aloud)

**Review by anxolin — COMMENTED** [review]
👍
