### PR TITLE
fix: fix graph for settlement contract trades

### LINKED ISSUE #491: Explorer crashes when open a TX details
Open https://explorer.cow.fi/goerli/tx/0xd78b614d0d5c39d55c516653e8674b73133d2c9bbdf302e5be036de7c6b304e6/?tab=graph

**AR**: the app is crashed

**ER**: the  TX is opened

### PR DESCRIPTION
**Pull request by alfetopito**
# Summary

Closes #491 

Fixing graph visualization for settlements where the settlement contract is also a trader
Screenshot 2023-05-26 at 16 02 16

Also adding error handling so if the graph ever fails, we'll not crash the app and show an error msg instead:
Screenshot 2023-05-26 at 15 56 27

# To Test

1. Open this trade `0xd78b614d0d5c39d55c516653e8674b73133d2c9bbdf302e5be036de7c6b304e6`
2. Check the graph visualization
* It should not crash the app
* It should show trades leading from COW to itself

### CODE REVIEW

**Review by elena-zh — APPROVED** [review]
Hey @alfetopito , great!
The app is not crashed. The graph sometimes can be hard to [read](https://explorer-dev-git-491-fix-graph-for-settlement-co-c0e7d8-cowswap.vercel.app/tx/0x54450bc55a83276344a4e27b951a82d0d5e1927af0126aaac64b1417eb369868/?tab=graph), but  a user can zoom in and out it, and change a view.

Also, was not able to test a 'failed to lead' scenario. I tried blocking requests URLs and switched the internet off, it did not help me to reproduce the case. 

Thanks

File: src/apps/explorer/components/TransanctionBatchGraph/index.tsx [hunk 1]
```diff
@@ -303,16 +304,22 @@ function TransanctionBatchGraph({
   )
 
   useEffect(() => {
```
Comment (anxolin) [inline src/apps/explorer/components/TransanctionBatchGraph/index.tsx:306]: ubernit: it would be probably nice to move all the effect to a custom hook to keep the component simpler

File: src/apps/explorer/components/TransanctionBatchGraph/index.tsx [hunk 2]
```diff
@@ -303,16 +304,22 @@ function TransanctionBatchGraph({
...
+
+      setElements(getNodes(txSettlement, networkId, heightSize, layout.name))
+      if (resetZoom) {
+        updateLayout(cy, layout.name)
+      }
+      removePopper(cyPopperRef)
+      setResetZoom(null)
+    } catch (e) {
+      console.error(`Failed to build graph`, e)
+      setFailedToLoadGraph(true)
```
Comment (anxolin) [inline src/apps/explorer/components/TransanctionBatchGraph/index.tsx:321]: thanks for addressing also this.

Should we have, maybe in another PR, an app-level https://legacy.reactjs.org/docs/error-boundaries.html
I thought we did. 

If we don't handle the errors, there should be a last resource boundary so the app don't look so broken (white screen)

**Review by shoom3301 — APPROVED** [review]

**Review by anxolin — APPROVED** [review]
As we discussed earlier, i think this graph will be way more visible if we create another node for the settlement. 

This way, we can see a difference between the "CoW Protocol: Settlement" (or "CoW Protocol: Batch" --> we could brainstorm on names) and just "CoW Protocol" for this contract acting as a trader.

This way, we can see how it sends shitcoins to the "CoW Protocol: Settlement" and receive WETH 

If we use the same node, its hard to visualise.


SOFT APPROVING, just because I think this PR fixes the issues, and this can be re-iterated

File: src/apps/explorer/components/TransanctionBatchGraph/index.tsx (hunk 2 above)
Comment (alfetopito) [reply src/apps/explorer/components/TransanctionBatchGraph/index.tsx:321]: Yeah, that was my initial approach, using Sentry's Error boundary because there's no standard way to do that in react other than with Class based components

See [this](https://stackoverflow.com/questions/48482619/how-can-i-make-use-of-error-boundaries-in-functional-react-components) and [this](https://react-typescript-cheatsheet.netlify.app/docs/basic/getting-started/error_boundaries/)

Wanted to have a more localized boundary to not break the UI completely. In the end, handling in the component was enough.

Will create an issue for handling this at the top level.

Comment (alfetopito) [reply src/apps/explorer/components/TransanctionBatchGraph/index.tsx]: https://github.com/cowprotocol/explorer/issues/503

File: src/apps/explorer/components/TransanctionBatchGraph/index.tsx (hunk 1 above)
Comment (alfetopito) [reply src/apps/explorer/components/TransanctionBatchGraph/index.tsx]: Did a very basic refactor - simply moving the code to a hooks and utils file.
Not worth to spend more time on this right now IMO.

**Comment by alfetopito** [comment]
I will merge as this fix the app crashing and continue working on improving the display in another PR
