### PR TITLE
[Batch Viewer] Fix multiple AMM's interactions not visible

### LINKED ISSUE #72: [Batch Viewer] AMMs nodes are displayed only once when involved in multiple interactions
**Description**
From @fleupold's comment
> Hi, it looks like in the transaction batch view we are only showing 1 interaction when the same address is involved in 2 interactions (e.g. when the Balancer Vault is used for 2 consecutive interactions). E.g. https://explorer.cow.fi/tx/0x99edc43f8ac89986fea0f433f2e87d09483090a776e152e50898e721f9b50210 is missing the WETH<>USDC balancer interaction.

**How to Reproduce**
1. Go to https://explorer.cow.fi/tx/0x99edc43f8ac89986fea0f433f2e87d09483090a776e152e50898e721f9b50210
2. Click on `Show Batch Viewer`
3. `Vault` Balancer node is only displayed once on the `WETH<>NATION` pair and the `WETH<>USDC` pair is missing

**Expected behavior**
Balancer's `Vault` should be displayed twice for the pairs  `WETH<>NATION` and `WETH<>USDC`

**Screenshots**
image

**Additional context**
When creating the graph nodes in https://github.com/cowprotocol/explorer/blob/develop/src/apps/explorer/components/TransanctionBatchGraph/index.tsx#L71-L77 addresses are mapped to ids and they shouldn't as they can appear more than once.

### PR DESCRIPTION
**Pull request by ramirotw**
# Summary

Closes #72 

image

# To Test
Open the Batch Viewer in https://pr78--gpui.review.gnosisdev.com/tx/0x8bb4f9644bdf19684d66c55133ded17c198e36069a502f903311eb07ed978145 and there should be multiple interactions in the Balancer's Vault

### CODE REVIEW

**Review by alfetopito — APPROVED** [review]

File: src/apps/explorer/components/TransanctionBatchGraph/styled.ts [hunk 1]
```diff
@@ -25,7 +25,7 @@ export function STYLESHEET(theme: DefaultTheme): Stylesheet[] {
         width: 2,
         'target-arrow-shape': 'triangle',
         'target-arrow-color': theme.grey,
-        'curve-style': 'unbundled-bezier',
+        'curve-style': 'bezier',
```
Comment (alongoni) [inline src/apps/explorer/components/TransanctionBatchGraph/styled.ts:28]: Not sure about this change:
image
Before (with: `'curve-style': 'unbundled-bezier'` )
image

Comment (ramirotw) [reply src/apps/explorer/components/TransanctionBatchGraph/styled.ts:28]: Yes it looks worse but without it you keep having the same reported issue. Could you see if there's a way to make them look similar? Maybe we could suggest merging the 2 arrows into 1 as we discussed.

**Comment by elena-zh** [comment]
Hey @ramirotw , great changes!
But I'd agree with @alongoni that overlapping elements do not look good. Moreover, they are not adjustable when zoom in/out the diagram. 

Also, I have noticed that ETH is displayed as WETH on the diagram: 
eth

**Comment by ramirotw** [comment]
> But I'd agree with @alongoni that overlapping elements do not look good. Moreover, they are not adjustable when zoom in/out the diagram.
> Mobile view:
> image

Yes, we still need to improve the layout, even more on mobile. I have some ideas to reduce the labels and arrows count and combine them into 1 bidirectional arrow having a `sellToken<>buyToken` label. For batches like the above that will improve things, but we still need research on better ways to organize the nodes, we have a [ticket](https://github.com/cowprotocol/explorer/issues/61) for that and will probably be for the next sprint.

> Also, I have noticed that ETH is displayed as WETH on the diagram:
> eth

It's indeed WETH:
```json
{
  "owner": "0x8668eb7a9cde59618f4c187415641063c02f41c2",
  "sellToken": "0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2",
  "buyToken": "0xa0b86991c6218b36c1d19d4a2e9eb0ce3606eb48",
  "sellAmount": "3481348765869705828",
  "buyAmount": "12125367336",
  "feeAmount": "12181348040899292",
  "orderUid": "0x686dd49dcd2d6b4b3ad49e18a3c8c1c130d3f6a1d66103936c20591ef98a831d8668eb7a9cde59618f4c187415641063c02f41c2624ae6eb"
}
```

**Comment by ramirotw** [comment]
@elena-zh are you ok to merge this and work on improving the general layout and overlapping in the new sprint?

**Comment by elena-zh** [comment]
@ramirotw , I'm not sure about it. 
Actually, if me merge this, it will go to the release. And we will receive user's complaints on it, I guess. 
But let ask @alfetopito opinion about this.

**Comment by alfetopito** [comment]
I think it's worth to move on as is since it fixes one bug, albeit making the visualization a bit harder in some cases.
